[package]
name = "twinleaf"
version = "1.4.1"
edition = "2021"
license = "MIT"
description = "Library for working with the Twinleaf I/O protocol and Twinleaf quantum sensors." 
homepage = "https://twinleaf.com"
repository = "https://github.com/twinleaf/twinleaf-rust"
readme = "README.md"

[dependencies]
crossbeam = "0.8"
mio-serial = "5.0"
crc = "3.2"
num_enum = "0.7"

[dependencies.mio]
version = "1.0"
features = ["os-poll", "net"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["commapi", "handleapi", "winbase"] }
