name: Rust

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev
      - name: Build
        run: cargo build --all --release --verbose
      - name: Strip binaries
        if: matrix.platform != 'windows-latest'
        run: |
          strip target/release/tio
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: twinleaf-tools.${{ matrix.platform }}
          path: |
            target/release/tio
            target/release/tio.exe

  completions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev zsh bash-completion

      - name: Generate and check completions
        working-directory: twinleaf-tools
        run: ./build-completions.sh

      - name: Ensure new dynamic completions are committed
        run: |
          if ! git diff --quiet --exit-code -- twinleaf-tools/completion-scripts/; then
            echo "::error::New dynamic completions are not committed. Run twinleaf-tools/build-completions.sh and commit"
            exit 1
          fi
